-- via grab 
create table "TEST".APPUSER
(
	USERNAME VARCHAR(255),
	PASSWORD VARCHAR(255),
	USERID NUMERIC(20) not null primary key
)

CREATE TABLE APP2USER (USERNAME VARCHAR(255), PASSWORD VARCHAR(255), USERID DECIMAL(20) NOT NULL, PRIMARY KEY (USERID));
CREATE TABLE APPUSER (USERNAME VARCHAR(255), PASSWORD VARCHAR(255), USERID DECIMAL(20) NOT NULL, PRIMARY KEY (USERID));


-- via view data danach show sql script for insert
INSERT INTO TEST.APPUSER (USERNAME, PASSWORD, USERID) 
	VALUES ('test', 'test', 1);
INSERT INTO TEST.APPUSER (USERNAME, PASSWORD, USERID) 
	VALUES ('test2', 'test2', 2);
